# Default initial positions for velma's ros2_control fake system

initial_positions:
  left_arm_0_joint: 0
  left_arm_1_joint: 0
  left_arm_2_joint: 0
  left_arm_3_joint: 0
  left_arm_4_joint: 0
  left_arm_5_joint: 0
  left_arm_6_joint: 0
  right_arm_0_joint: 0
  right_arm_1_joint: 0
  right_arm_2_joint: 0
  right_arm_3_joint: 0
  right_arm_4_joint: 0
  right_arm_5_joint: 0
  right_arm_6_joint: 0
  torso_0_joint: 0