# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arms_torso_effort:
      type: wut_velma_effort_controller/WutVelmaEffortController

    arms_torso_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arms_torso_trajectory_controller:
  ros__parameters:
    joints:
      - torso_0_joint
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint

    command_joints:
      - arms_torso_effort/torso_0_joint
      - arms_torso_effort/left_arm_0_joint
      - arms_torso_effort/left_arm_1_joint
      - arms_torso_effort/left_arm_2_joint
      - arms_torso_effort/left_arm_3_joint
      - arms_torso_effort/left_arm_4_joint
      - arms_torso_effort/left_arm_5_joint
      - arms_torso_effort/left_arm_6_joint
      - arms_torso_effort/right_arm_0_joint
      - arms_torso_effort/right_arm_1_joint
      - arms_torso_effort/right_arm_2_joint
      - arms_torso_effort/right_arm_3_joint
      - arms_torso_effort/right_arm_4_joint
      - arms_torso_effort/right_arm_5_joint
      - arms_torso_effort/right_arm_6_joint

    command_interfaces:
      - position
      - velocity
      - acceleration

    state_interfaces:
      - position
      - velocity

    allow_nonzero_velocity_at_trajectory_end: true
    allow_partial_joints_goal: true
    interpolation_method: splines

    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.5

arms_torso_effort:
  ros__parameters:
    joints:
      - torso_0_joint
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    chainable_command_interfaces:
      - position
      - velocity
      - acceleration

    collision_distance: 0.025

    collision_model_links:
      - torso_link0
      - torso_link0
      - head_bounding_sphere
      - calib_right_arm_base_link
      - right_arm_1_link
      - right_arm_2_link
      - right_arm_3_link
      - right_arm_4_link
      - right_arm_5_link
      - right_arm_6_link
      - calib_left_arm_base_link
      - left_arm_1_link
      - left_arm_2_link
      - left_arm_3_link
      - left_arm_4_link
      - left_arm_5_link
      - left_arm_6_link
      - left_gripper_mount_link
      - right_gripper_mount_link
      - right_HandPalmLink
      - right_HandFingerThreeKnuckleTwoLink
      - right_HandFingerThreeKnuckleThreeLink
      - right_HandFingerOneKnuckleTwoLink
      - right_HandFingerOneKnuckleThreeLink
      - right_HandFingerTwoKnuckleTwoLink
      - right_HandFingerTwoKnuckleThreeLink
      - left_HandPalmLink
      - left_HandFingerThreeKnuckleTwoLink
      - left_HandFingerThreeKnuckleThreeLink
      - left_HandFingerOneKnuckleTwoLink
      - left_HandFingerOneKnuckleThreeLink
      - left_HandFingerTwoKnuckleTwoLink
      - left_HandFingerTwoKnuckleThreeLink

    collision_model_col0: [1.0000, 0.2000, 0.0000, 0.0000, 1.3000, 0.0000, 0.0000, 0.3000]
    collision_model_col1: [0.4000, 0.1800, -0.1000, 0.0000, 0.6500, -0.1000, 0.0000, 0.2500]
    collision_model_col2: [0.2300, 0.0400, 0.0000, 1.5700]
    collision_model_col3: [0.1100, 0.0700, 0.0000, 0.0000, 0.1100, 0.0000, 0.0000, 0.0000]
    collision_model_col4: [0.2080, 0.0650, 0.0000, -0.0357, 0.2019, 0.0000, 0.0057, -0.0019]
    collision_model_col5: [0.2080, 0.0650, 0.0000, -0.0057, 0.2019, 0.0000, 0.0357, -0.0019]
    collision_model_col6: [0.2080, 0.0650, 0.0000, 0.0357, 0.2019, 0.0000, -0.0057, -0.0019]
    collision_model_col7: [0.2080, 0.0650, 0.0000, 0.0057, 0.2019, 0.0000, -0.0357, -0.0019]
    collision_model_col8: [0.1980, 0.0650, 0.0000, -0.0353, 0.1919, 0.0000, 0.0053, -0.0019]
    collision_model_col9: [0.0000, 0.0800, 0.0000, 0.0100, 0.0000, 0.0000, 0.0100, 0.0000]
    collision_model_col10: [0.1100, 0.0700, 0.0000, 0.0000, 0.1100, 0.0000, 0.0000, 0.0000]
    collision_model_col11: [0.2080, 0.0650, 0.0000, -0.0357, 0.2019, 0.0000, 0.0057, -0.0019]
    collision_model_col12: [0.2080, 0.0650, 0.0000, -0.0057, 0.2019, 0.0000, 0.0357, -0.0019]
    collision_model_col13: [0.2080, 0.0650, 0.0000, 0.0357, 0.2019, 0.0000, -0.0057, -0.0019]
    collision_model_col14: [0.2080, 0.0650, 0.0000, 0.0057, 0.2019, 0.0000, -0.0357, -0.0019]
    collision_model_col15: [0.1980, 0.0650, 0.0000, -0.0353, 0.1919, 0.0000, 0.0053, -0.0019]
    collision_model_col16: [0.0000, 0.0800, 0.0000, 0.0100, 0.0000, 0.0000, 0.0100, 0.0000]
    collision_model_col17: [0.0800, 0.0550, 0.0600, 0.0000, -0.0100, -0.0200, 0.0000, -0.0100]
    collision_model_col18: [0.0800, 0.0550, 0.0600, 0.0000, -0.0100, -0.0200, 0.0000, -0.0100]
    collision_model_col19: [0.0600, 0.0000, 0.0000, 0.0300]
    collision_model_col20: [0.0600, 0.0150, 0.0600, 0.0000, 0.0000, 0.0000, 0.0000, -0.0000]
    collision_model_col21: [0.0500, 0.0150, 0.0500, 0.0000, 0.0000, 0.0000, 0.0000, -0.0000]
    collision_model_col22: [0.0600, 0.0150, 0.0600, 0.0000, 0.0000, 0.0000, 0.0000, -0.0000]
    collision_model_col23: [0.0500, 0.0150, 0.0500, 0.0000, 0.0000, 0.0000, 0.0000, -0.0000]
    collision_model_col24: [0.0600, 0.0150, 0.0600, 0.0000, 0.0000, 0.0000, 0.0000, -0.0000]
    collision_model_col25: [0.0500, 0.0150, 0.0500, 0.0000, 0.0000, 0.0000, 0.0000, -0.0000]
    collision_model_col26: [0.0600, 0.0000, 0.0000, 0.0300]
    collision_model_col27: [0.0600, 0.0150, 0.0600, 0.0000, 0.0000, 0.0000, 0.0000, -0.0000]
    collision_model_col28: [0.0500, 0.0150, 0.0500, 0.0000, 0.0000, 0.0000, 0.0000, -0.0000]
    collision_model_col29: [0.0600, 0.0150, 0.0600, 0.0000, 0.0000, 0.0000, 0.0000, -0.0000]
    collision_model_col30: [0.0500, 0.0150, 0.0500, 0.0000, 0.0000, 0.0000, 0.0000, -0.0000]
    collision_model_col31: [0.0600, 0.0150, 0.0600, 0.0000, 0.0000, 0.0000, 0.0000, -0.0000]
    collision_model_col32: [0.0500, 0.0150, 0.0500, 0.0000, 0.0000, 0.0000, 0.0000, -0.0000]

    collision_model_groups: 2

    collision_model_group0:
      - left_arm_1_link
      - left_arm_2_link
      - left_arm_3_link
      - left_arm_4_link
      - left_arm_5_link
      - left_arm_6_link
      - left_gripper_mount_link
      - left_HandPalmLink
      - left_HandFingerOneKnuckleTwoLink
      - left_HandFingerOneKnuckleThreeLink
      - left_HandFingerTwoKnuckleTwoLink
      - left_HandFingerTwoKnuckleThreeLink
      - left_HandFingerThreeKnuckleTwoLink
      - left_HandFingerThreeKnuckleThreeLink

    collision_model_group1:
      - right_arm_1_link
      - right_arm_2_link
      - right_arm_3_link
      - right_arm_4_link
      - right_arm_5_link
      - right_arm_6_link
      - right_gripper_mount_link
      - right_HandPalmLink
      - right_HandFingerOneKnuckleTwoLink
      - right_HandFingerOneKnuckleThreeLink
      - right_HandFingerTwoKnuckleTwoLink
      - right_HandFingerTwoKnuckleThreeLink
      - right_HandFingerThreeKnuckleTwoLink
      - right_HandFingerThreeKnuckleThreeLink

head_controller:
  ros__parameters:
    joints:
      - head_pan_joint
      - head_tilt_joint

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false
    interpolation_method: splines


left_hand_controller:
  ros__parameters:
    joints:
      - left_HandFingerOneKnuckleOneJoint
      - left_HandFingerOneKnuckleTwoJoint
      - left_HandFingerOneKnuckleThreeJoint
      - left_HandFingerThreeKnuckleTwoJoint
      - left_HandFingerThreeKnuckleThreeJoint
      - left_HandFingerTwoKnuckleOneJoint
      - left_HandFingerTwoKnuckleTwoJoint
      - left_HandFingerTwoKnuckleThreeJoint

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false
    interpolation_method: splines

    constraints:
      goal_time: 0.1
      stopped_velocity_tolerance: 0.01

      left_HandFingerOneKnuckleTwoJoint:
        trajectory: 0.5236  # 30 deg.
        goal: 0.5236
      left_HandFingerOneKnuckleThreeJoint:
        trajectory: 0.5236
        goal: 0.5236
      left_HandFingerTwoKnuckleTwoJoint:
        trajectory: 0.5236  # 30 deg.
        goal: 0.5236
      left_HandFingerTwoKnuckleThreeJoint:
        trajectory: 0.5236
        goal: 0.5236
      left_HandFingerThreeKnuckleTwoJoint:
        trajectory: 0.5236  # 30 deg.
        goal: 0.5236
      left_HandFingerThreeKnuckleThreeJoint:
        trajectory: 0.5236
        goal: 0.5236

right_hand_controller:
  ros__parameters:
    joints:
      - right_HandFingerOneKnuckleOneJoint
      - right_HandFingerOneKnuckleTwoJoint
      - right_HandFingerOneKnuckleThreeJoint
      - right_HandFingerThreeKnuckleTwoJoint
      - right_HandFingerThreeKnuckleThreeJoint
      - right_HandFingerTwoKnuckleOneJoint
      - right_HandFingerTwoKnuckleTwoJoint
      - right_HandFingerTwoKnuckleThreeJoint

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false
    interpolation_method: splines

    constraints:
      goal_time: 0.1
      stopped_velocity_tolerance: 0.01

      right_HandFingerOneKnuckleTwoJoint:
        trajectory: 0.5236  # 30 deg.
        goal: 0.5236
      right_HandFingerOneKnuckleThreeJoint:
        trajectory: 0.5236
        goal: 0.5236
      right_HandFingerTwoKnuckleTwoJoint:
        trajectory: 0.5236  # 30 deg.
        goal: 0.5236
      right_HandFingerTwoKnuckleThreeJoint:
        trajectory: 0.5236
        goal: 0.5236
      right_HandFingerThreeKnuckleTwoJoint:
        trajectory: 0.5236  # 30 deg.
        goal: 0.5236
      right_HandFingerThreeKnuckleThreeJoint:
        trajectory: 0.5236
        goal: 0.5236
