# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arms_torso_effort:
      type: wut_velma_effort_controller/WutVelmaEffortController

    arms_torso_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    computed_cart_torque_controller:
      type: wut_velma_effort_controller/CartTorqueController

    cartesian_trajectory_generator:
      type: cartesian_trajectory_generator/CartesianTrajectoryGenerator

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # For tests only
    test_A:
      type: wut_velma_effort_controller/TestChainableController
    test_B:
      type: wut_velma_effort_controller/TestChainableController
    test_C:
      type: wut_velma_effort_controller/TestChainableController

# For tests only
# Chain test:
# Structure 1:
#   command: C -> B -> A -> HW
#   state: HW -> A -> C
# Structure 2:
#   command: C -> B -> A -> HW
#   state: HW -> A -> B -> C
# Structure 3:
#   command: C -> B -> A -> HW
#   state: HW -> A, HW -> B, HW -> C
test_A:
  ros__parameters:
    joints:
      - head_pan_joint
      - head_tilt_joint
    require_command_interfaces: true
    require_state_interfaces: true

test_B:
  ros__parameters:
    joints:
      - head_pan_joint
      - head_tilt_joint
    require_command_interfaces: true
    downstream_command_controller: test_A
    require_state_interfaces: true
    # downstream_state_controller: test_A

test_C:
  ros__parameters:
    joints:
      - head_pan_joint
      - head_tilt_joint
    require_command_interfaces: true
    downstream_command_controller: test_B
    require_state_interfaces: true
    # downstream_state_controller: test_B

computed_cart_torque_controller:
  ros__parameters:
    # Tu parametry Twojego kontrolera momentowego.
    # Musi eksportować reference interfaces zgodne z nazwami powyżej.
    joints:
      - torso_0_joint
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

cartesian_trajectory_generator:
  ros__parameters:
    downstream_controller: computed_cart_torque_controller


arms_torso_trajectory_controller:
  ros__parameters:
    joints:
      - torso_0_joint
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint

    # To są "joint names" po stronie komend.
    # JTC będzie zapisywał do:
    # computed_torque_controller/joint1/position itd.
    command_joints:
      - arms_torso_effort/torso_0_joint
      - arms_torso_effort/left_arm_0_joint
      - arms_torso_effort/left_arm_1_joint
      - arms_torso_effort/left_arm_2_joint
      - arms_torso_effort/left_arm_3_joint
      - arms_torso_effort/left_arm_4_joint
      - arms_torso_effort/left_arm_5_joint
      - arms_torso_effort/left_arm_6_joint
      - arms_torso_effort/right_arm_0_joint
      - arms_torso_effort/right_arm_1_joint
      - arms_torso_effort/right_arm_2_joint
      - arms_torso_effort/right_arm_3_joint
      - arms_torso_effort/right_arm_4_joint
      - arms_torso_effort/right_arm_5_joint
      - arms_torso_effort/right_arm_6_joint

    command_interfaces:
      - position
      - velocity
      - acceleration

    # To są fizyczne stany robota, nie wirtualne referencje.
    state_interfaces:
      - position
      - velocity

    allow_nonzero_velocity_at_trajectory_end: true
    allow_partial_joints_goal: true
    interpolation_method: splines

    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.5

arms_torso_effort:
  ros__parameters:
    joints:
      - torso_0_joint
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    # parametr własny kontrolera:
    chainable_command_interfaces:
      - position
      - velocity
      - acceleration

head_controller:
  ros__parameters:
    joints:
      - head_pan_joint
      - head_tilt_joint

    # To są "joint names" po stronie komend.
    # JTC będzie zapisywał do:
    # computed_torque_controller/joint1/position itd.

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false
    interpolation_method: splines


left_hand_controller:
  ros__parameters:
    joints:
      - left_HandFingerOneKnuckleOneJoint
      - left_HandFingerOneKnuckleTwoJoint
      - left_HandFingerOneKnuckleThreeJoint
      - left_HandFingerThreeKnuckleTwoJoint
      - left_HandFingerThreeKnuckleThreeJoint
      - left_HandFingerTwoKnuckleOneJoint
      - left_HandFingerTwoKnuckleTwoJoint
      - left_HandFingerTwoKnuckleThreeJoint

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false
    interpolation_method: splines

right_hand_controller:
  ros__parameters:
    joints:
      - right_HandFingerOneKnuckleOneJoint
      - right_HandFingerOneKnuckleTwoJoint
      - right_HandFingerOneKnuckleThreeJoint
      - right_HandFingerThreeKnuckleTwoJoint
      - right_HandFingerThreeKnuckleThreeJoint
      - right_HandFingerTwoKnuckleOneJoint
      - right_HandFingerTwoKnuckleTwoJoint
      - right_HandFingerTwoKnuckleThreeJoint

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false
    interpolation_method: splines

# arms_torso_controller:
#   ros__parameters:
#     joints:
#       - torso_0_joint
#       - left_arm_0_joint
#       - left_arm_1_joint
#       - left_arm_2_joint
#       - left_arm_3_joint
#       - left_arm_4_joint
#       - left_arm_5_joint
#       - left_arm_6_joint
#       - right_arm_0_joint
#       - right_arm_1_joint
#       - right_arm_2_joint
#       - right_arm_3_joint
#       - right_arm_4_joint
#       - right_arm_5_joint
#       - right_arm_6_joint
#     command_interfaces:
#       [position]
#     state_interfaces:
#       [position, velocity]
#     allow_nonzero_velocity_at_trajectory_end: true
# arms_controller:
#   ros__parameters:
#     joints:
#       - left_arm_0_joint
#       - left_arm_1_joint
#       - left_arm_2_joint
#       - left_arm_3_joint
#       - left_arm_4_joint
#       - left_arm_5_joint
#       - left_arm_6_joint
#       - right_arm_0_joint
#       - right_arm_1_joint
#       - right_arm_2_joint
#       - right_arm_3_joint
#       - right_arm_4_joint
#       - right_arm_5_joint
#       - right_arm_6_joint
#     command_interfaces:
#       []
#     state_interfaces:
#       []
#     allow_nonzero_velocity_at_trajectory_end: true
# left_arm_torso_controller:
#   ros__parameters:
#     joints:
#       - torso_0_joint
#       - left_arm_0_joint
#       - left_arm_1_joint
#       - left_arm_2_joint
#       - left_arm_3_joint
#       - left_arm_4_joint
#       - left_arm_5_joint
#       - left_arm_6_joint
#     command_interfaces:
#       []
#     state_interfaces:
#       []
#     allow_nonzero_velocity_at_trajectory_end: true
# right_arm_torso_controller:
#   ros__parameters:
#     joints:
#       - torso_0_joint
#       - right_arm_0_joint
#       - right_arm_1_joint
#       - right_arm_2_joint
#       - right_arm_3_joint
#       - right_arm_4_joint
#       - right_arm_5_joint
#       - right_arm_6_joint
#     command_interfaces:
#       []
#     state_interfaces:
#       []
#     allow_nonzero_velocity_at_trajectory_end: true
# left_arm_controller:
#   ros__parameters:
#     joints:
#       - left_arm_0_joint
#       - left_arm_1_joint
#       - left_arm_2_joint
#       - left_arm_3_joint
#       - left_arm_4_joint
#       - left_arm_5_joint
#       - left_arm_6_joint
#     command_interfaces:
#       []
#     state_interfaces:
#       []
#     allow_nonzero_velocity_at_trajectory_end: true
# right_arm_controller:
#   ros__parameters:
#     joints:
#       - right_arm_0_joint
#       - right_arm_1_joint
#       - right_arm_2_joint
#       - right_arm_3_joint
#       - right_arm_4_joint
#       - right_arm_5_joint
#       - right_arm_6_joint
#     command_interfaces:
#       []
#     state_interfaces:
#       []
#     allow_nonzero_velocity_at_trajectory_end: true
